### ISSUE TITLE
Coulnd't deploy useing v0.1.4 binary

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/go-rmb#20]
couldn't deploy using v0.1.4 binary 
![image](https://user-images.githubusercontent.com/46320202/142761710-ae15331b-e609-48fd-bf4e-8b581760f0ae.png)

**Comment by dmahmouali** [comment]
The issue was in the default substrate URL, fixed in the new release https://github.com/threefoldtech/go-rmb/releases/tag/v0.1.5
please, check and verify
